# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["<devrel@fastly.com>"]
description = "An empty application template for the Fastly Compute C++ SDK which returns a 200 OK response."
language = "cpp"
manifest_version = 3
name = "Empty starter for C++"

[scripts]
post_init = "cmake --preset wasi"
build = "cmake --build build && cp build/main.wasm bin/main.wasm"
