# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["<oss@fastly.com>"]
description = "Implements realtime handlers for SSE, WebSockets, etc., powered by Fanout"
language = "javascript"
manifest_version = 3
name = "Realtime starter for JavaScript"

[catalog]
topics = ["real-time"]

[local_server.pushpin]
enable = true

[local_server.backends]
[local_server.backends.origin]
url = "https://example.com/"
override_host = "example.com"

[local_server.backends.self]
url = "http://localhost:7676/"
override_host = "localhost:7676"

[setup.backends]
[setup.backends.origin]
[setup.backends.self]

[setup.products]
[setup.products.fanout]
enable = true

[scripts]
build = "npm run build"
post_init = "npm install"
