# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["oss@fastly.com"]
description = "A Go starter kit that uses Fastly's KV Store."
language = "go"
manifest_version = 2
name = "KV Store in Go"
service_id = ""

[scripts]
  env_vars = ["GOARCH=wasm", "GOOS=wasip1"]
  build = "go build -o bin/main.wasm ."
  post_init = "go get github.com/fastly/compute-sdk-go@latest"

[local_server]
[local_server.kv_stores]
[[local_server.kv_stores.my-store]]
  key = "readme"
  path = "./README.md"

[setup]
[setup.kv_stores]
[setup.kv_stores.my-store]
  description = "My first kv store"
